# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ExamenApp' do


use_frameworks!


pod 'Alamofire', '~> 3.2.1'

end

target 'ExamenAppTests' do

end

target 'ExamenAppUITests' do

end

